name: dorianberesford
favicon: null
layout_spectrum: 0.060767309507355094
typography_spectrum: 0.6952848413493484
title: Dorian Beresford
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed0015'
    - '#ffffff'
    - '#f13e4e'
    - '#800000'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.04274036083370447
  saturation: 0.8614216106943786
  rhythmicContrast: 0.4085417855530977
purpose: []
